name: "i^2: I keep IT real. And simple."
description: Thoughts on software design, architecture and programming that I just can't hold inside anymore.
url: http://blog.korbakov.com
markdown: redcarpet
pygments: true